#!/usr/bin/env bash
# Change localhost and facebook.com resolution

cp /etc/hosts /tmp/hosts

sed -i 's/^127\.0\.0\.1.*/127.0.0.2 localhost/' /tmp/hosts

echo "8.8.8.8 facebook.com" >> /tmp/hosts

cat /tmp/hosts > /etc/hosts
